### ISSUE TITLE
Not working under systemd

### ISSUE THREAD

**Issue by Bohmthedudevulture** [IHaskell/IHaskell#1344] opened 2022-05-10 18:16 UTC
The kernel appears to work perfectly when I start the Jupyter Server from the command line, but when I setup Jupyter to run from a systemd service the Kernel crashes all the time.

**Comment by vaibhavsagar** [comment] 2022-05-11 01:41
This is out of scope for support, since there are a bunch of moving parts at play and it's extremely unlikely that the issue is with IHaskell.

**Closed by vaibhavsagar** 2022-05-11 01:41 UTC
